### ISSUE TITLE
Question About App Backgrounding Crash

### ISSUE THREAD

**Issue by mikefogg** [acktie/Acktie-Mobile-Android-Barcode#1]
I know you guys are probably not doing much more work on this having moved off of titanium (from what I remember), so this is more just a question incase you have any thoughts (as it's causing a much larger issue than I assumed it would :) ).

I'm seeing a crash happen a lot any time I'm on a page with a BarcodeView on it and I background the app. The crash seems to happen as soon as I open the app back up (or possibly after backgrounding, I'm not quite sure yet as I don't notice it until I open it again).

The log coming from the crash is:

```
0   
java.lang.NullPointerException
1   
at com.acktie.mobile.android.camera.CameraSurfaceView.surfaceCreated(CameraSurfaceView.java:87)
2   
at android.view.SurfaceView.updateWindow(SurfaceView.java:586)
3   
at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:236)
4   
at android.view.View.dispatchWindowVisibilityChanged(View.java:7802)
5   
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)
6   
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)
7   
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)
8   
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)
9   
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)
10  
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1080)

```

I'm going to keep looking around, it looks somewhat related to this (http://stackoverflow.com/questions/7850419/android-surfaceview-crashes-when-go-to-background) but if anything comes to mind that mind help I'd be extremely grateful!

Thanks!

**Comment by TNuzzi** [comment]
Hey Mike, I think we have seen this.  Have you tried to "stop" the scanner prior to backgrounding the app?  The problem is the module does not have a valid surfaceview.

Thanks,

Tony

**Comment by mikefogg** [comment]
@TNuzzi , hmm, that's a great idea! I haven't given that a try yet (honestly, I didn't know there was a stop() function until you mentioned that :) ). The only problem I'm seeing is that I'm not entirely sure how I could tell that an app is about to background. For example, if I hit that "Home" button on the phone I don't know if there's a listener to say "before you do that, stop the camera". The app seems to be crashing right as it goes into the background.

Thanks for helping to diagnose the problem! I figured that was the case, but I'm just not sure how to fix it...

**Comment by TNuzzi** [comment]
@mikefogg I think you can use pause or paused global events to catch when your app is backgrounded.  http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.App-event-pause

**Comment by mikefogg** [comment]
@TNuzzi, again, thanks for the help! I did take a look at that and tried it out but it's only an iOS feature unfortunately. What I've figured out is that the cameraView.stop(); functionality will still kill it on backgrounding (I set a timeout of 3 seconds when the page opened to fire the stop() function).

What DID work, was calling stop(); then removing that view from the page and nulling it out. Unfortunately, there's no way to do that on background because of the lack of callbacks for pause/resume that can fire prior to changing the visibility of the camera view.

I'm curious if you know why the issue is happening in general? I know you mentioned it had to do with not having a valid surfaceview. Do you think this is an issue in the actual cameramanager (in https://github.com/acktie/Acktie-Zbar-Android) or something specific to this app? I'm assuming, after googling it, that this is a pretty common issue with the Surface View. I can play around with it but if you think of any spots that may be causing the issue I'd really appreciate any thoughts :)

**Comment by TNuzzi** [comment]
@mikefogg After thinking about it I wonder if the cameramanger should auto stop when the CameraSurfaceView is null.

**Comment by mikefogg** [comment]
@TNuzzi, ah! Ok so made some progress here, though not much:

I am having a bunch of trouble actually **building** my changes into the Acktie-ZBar-Android module (https://github.com/acktie/Acktie-Zbar-Android/blob/master/src/com/acktie/mobile/android/camera/CameraSurfaceView.java) on line 87 inside of the try/catch block but when I add this in it doesn't crash:

```
if(camera==null){
   camera = cameraManager.getCamera();
}
```

Though, I believe I'm building the dependencies incorrectly via maven as it ends up being around 16kb and not actually firing a success callback (even if I copy your code exactly). Would it be difficult for you to add that and run a build? Or maybe just let me know how you guys build it so I can take that approach, as mine doesn't seem to be packaging it up in a way that actually works (though I do see the camera, etc, just not actually scanning.

**Comment by mikefogg** [comment]
Ah, after poking around a bit more it looks like the version we're building with of the Acktie-Zbar-Android isn't the one that is built into the Barcode 1.4 module. The current codebase references com.google.zxing and the 1.4 version does not :)

I'm not sure if that has anything to do with it but I'm going to assume it probably does. Would you happen to have the code checked-in anywhere that was used to build the 1.4 module?

**Comment by mikefogg** [comment]
@TNuzzi, I'm closing this issue because I managed to get it to work without crashing by modifying the acktie.jar file using the code I pasted above.

Working version can be found at: https://github.com/mikefogg/Acktie-Zbar-Android (and built with Maven)
